import Head from 'next/head';
import Layout, {siteTitle} from '../components/layout';
import utilStyles from '../styles/utils.module.css';
import {getSortedPostsData} from '@/lib/posts';
import Link from 'next/link'
import Date from '../components/date'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

// export async function getStaticProps() {
//     const allPostsData = getSortedPostsData();
//     return {
//         props: {
//             allPostsData,
//         }
//     }
// }

export default function Home() {
    const allPostsData = getSortedPostsData();

    return (
      <></>
    );
}